### ISSUE TITLE
ModuleNotFoundError: No module named 'api_exceptions'

### ISSUE THREAD

**Issue by AL3XAND3R98** [Sibiryakanton/betfair_python_rest#1]
from api_exceptions.base_exception import BetFairAPIManagerException

fix

from ..api_exceptions.base_exception import BetFairAPIManagerException

**Comment by Sibiryakanton** [comment]
[https://github.com/Sibiryakanton/betfair_python_rest/commit/e4006fab471ce93968b2ff28e313b74826127cd5](url)
Thank you for your feedback
